# Generated by Django 4.1.11 on 2023-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hidden_images/')),
                ('encrypted_text', models.BinaryField()),
                ('aes_key', models.BinaryField()),
                ('num_encrypted_images', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
