# Generated by Django 4.1.11 on 2023-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hiddenimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenimage',
            name='num_encrypted_images',
        ),
        migrations.AlterField(
            model_name='hiddenimage',
            name='image',
            field=models.FileField(upload_to='hidden_images1/'),
        ),
    ]
