# Generated by Django 4.1.11 on 2023-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_hiddenimage_num_encrypted_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
